service: t212scraper
provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
plugins:
  - serverless-esbuild
  - serverless-offline
functions:
  t212scraper:
    handler: ./src/lambda.handler
